### PR TITLE
accept null or trimmed empty/non-empty string

### PR DESCRIPTION
**Pull request by mikeclimbrock**

### CODE REVIEW

**Comment by mikeclimbrock** [comment]
right - but i think we want to allow `empty` now as well

**Comment by mbryzek** [comment]
why not store empty as null?

**Comment by mikeclimbrock** [comment]
ok - we technically don't need a constraint, but thought it may be helpful so it remain explicit

in the application, we'll have something like this that returns the Option used in the query binding:
```
def emptyStringAsNull(value: String): Option[String] = {
    if(value.trim.isEmpty) {
      None
    } else {
      Some(value)
    }
  }
```

**Comment by mikeclimbrock** [comment]
alternatively, we can create a trigger - 
```
create trigger empty_trimmed_string_as_null before insert on cart_items
  for each row
    begin
      if new.product_type = '' then
        null;
     end if;
  end;
$$
```

**Comment by mbryzek** [comment]
I think the only thing we have to do in shopify is `value.getOrElse("")`

**Comment by mbryzek** [comment]
recommend closing

**Pull request closed without merging**
